version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: natanon/frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: natanon/backend

